# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://
date_format: "ordinal"
title: Coding World
subtitle: "Coding changes the world"
description: "Liu Ke's Blog"
keywords: Liu, Ke 
favicon: /favicon.ico
timezone: Asia/China
encoding: "utf-8"
side_bar_repo_limit: 4

# ---------------- #
#      Author      #
# ---------------- #
author: Liu, Ke
github_username: liu-ke
location: Stuttgart, Germany
email: liuke.coder@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: liu-ke/liu-ke.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
disqus_username:
netease_gentie_key: 
# 在使用网易云跟帖时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
